version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: "backend/.env"
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

